title: Mi primera pagina Web
author: GitHub User
email: your-email@domain.com
description: > # Esta es mi primera pagina web con Github.

# social links
twitter_username: your-twitter-handle
github_username:  your-github-handle

show_excerpts: true # set to false to remove excerpts on the homepage

theme: jekyll-theme-minimal
